### ISSUE TITLE
getting SyntaxError for bin.js

### ISSUE THREAD

**Issue by bumbleblue** [boowajs/boowa#2]
Tried to run this but bumped into this SyntaxError after the `boowa` command.
```
/usr/local/lib/node_modules/boowa/bin.js:25
      }]).then(async anwsers => {
               ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by ZhouHansen** [comment]
Could you provide your node version. boowa works with async functions, that means you should use node 7.6+

**Comment by bumbleblue** [comment]
oops! you're right, my bad!
